/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generator;

import constants.Constants;
import java.awt.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author thanhtd
 */
public class GeneratorFrame extends javax.swing.JFrame {

    /**
     * Creates new form SortingFrame
     */
    public GeneratorFrame() {
        initComponents();
        progressBar.setVisible(false);
        standAloneRunning = new StandAloneMode();
        distributedRunning = new DistributedMode();
        standAloneModeRadioBtn.setSelected(true);
        Constants.NUM_WORKERS = Integer.parseInt(numServerComboBox.getItemAt(numServerComboBox.getSelectedIndex()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        inputNumTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputContainer = new javax.swing.JTextArea();
        runBtn = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        performanceReport = new javax.swing.JTextArea();
        standAloneModeRadioBtn = new javax.swing.JRadioButton();
        distributedModeRadioBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        numServerComboBox = new javax.swing.JComboBox<>();
        fetchComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generator");
        setResizable(false);

        jLabel1.setText("Random size:");

        inputNumTxtField.setText("1000000");

        jLabel2.setText("Option:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("OutputList"));

        outputContainer.setColumns(20);
        outputContainer.setRows(5);
        jScrollPane2.setViewportView(outputContainer);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        runBtn.setText("Run");
        runBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runBtnActionPerformed(evt);
            }
        });

        progressBar.setIndeterminate(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Performance Report"));

        performanceReport.setColumns(20);
        performanceReport.setRows(5);
        jScrollPane1.setViewportView(performanceReport);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        buttonGroup1.add(standAloneModeRadioBtn);
        standAloneModeRadioBtn.setText("Single Mode");
        standAloneModeRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standAloneModeRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(distributedModeRadioBtn);
        distributedModeRadioBtn.setText("Distributed Mode");
        distributedModeRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributedModeRadioBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("#Workers");

        numServerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        numServerComboBox.setEnabled(false);
        numServerComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                numServerComboBoxItemStateChanged(evt);
            }
        });

        fetchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        fetchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Fetch to output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(inputNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(standAloneModeRadioBtn)
                        .addGap(0, 0, 0)
                        .addComponent(distributedModeRadioBtn)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(numServerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fetchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(inputNumTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(standAloneModeRadioBtn)
                    .addComponent(distributedModeRadioBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numServerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fetchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runBtn)
                            .addComponent(jLabel4))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runBtnActionPerformed
        num = 0;
        this.outputContainer.setText("");
        
        try {
            num = Integer.parseInt(inputNumTxtField.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "The input text must be a number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        SwingWorker worker = new SwingWorker() {

            @Override
            protected void done() {
                // Close the dialog
//                dialog.dispose();
                  progressBar.setVisible(false);
            }

            protected void process(List chunks) {
                // Here you can process the result of "doInBackGround()"
                // Set a variable in the dialog or etc.
            }

            @Override
            protected Object doInBackground() throws Exception {
                
                progressBar.setVisible(true);
                // Do the long running task here
                // Call "publish()" to pass the data to "process()"
                // return something meaningful
                String sperformanceReport = "";
                if (standAloneModeRadioBtn.isSelected()) {
                    //Running Stand alone
//                    standAloneRunning.setInitTime(initTime);
                    String res = standAloneRunning.run(num);
                    if (fetchComboBox.getSelectedIndex() == 0) {
                        outputContainer.setText(res);
                    }
                    sperformanceReport = standAloneRunning.getPerformanceReport();
                } else {
//                    System.out.println(Constants.NUM_WORKERS + " are working");
                    //Distributed mode
//                    distributedRunning.setInitTime(initTime);
                    String res = distributedRunning.run(num);
                    if (fetchComboBox.getSelectedIndex() == 0) {
                        outputContainer.setText(res);
                    }
                    sperformanceReport = distributedRunning.getPerformanceReport();
                }
                

                performanceReport.append(sperformanceReport);
                return null;
            }
        };
        
        worker.execute();
        
        
    }//GEN-LAST:event_runBtnActionPerformed

    private void distributedModeRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributedModeRadioBtnActionPerformed
        this.numServerComboBox.setEnabled(true);
    }//GEN-LAST:event_distributedModeRadioBtnActionPerformed

    private void standAloneModeRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standAloneModeRadioBtnActionPerformed
        this.numServerComboBox.setEnabled(false);
    }//GEN-LAST:event_standAloneModeRadioBtnActionPerformed

    private void numServerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_numServerComboBoxItemStateChanged
        Constants.NUM_WORKERS = Integer.parseInt(numServerComboBox.getItemAt(numServerComboBox.getSelectedIndex()));
    }//GEN-LAST:event_numServerComboBoxItemStateChanged

    private void fetchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fetchComboBoxActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton distributedModeRadioBtn;
    private javax.swing.JComboBox<String> fetchComboBox;
    private javax.swing.JTextField inputNumTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> numServerComboBox;
    private javax.swing.JTextArea outputContainer;
    private javax.swing.JTextArea performanceReport;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton runBtn;
    private javax.swing.JRadioButton standAloneModeRadioBtn;
    // End of variables declaration//GEN-END:variables
    private long initTime;
    
    private StandAloneMode standAloneRunning;
    private DistributedMode distributedRunning;
    private int num;
}
